name: CICD
on:
  workflow_dispatch:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Clone the code"
  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build using Docker
        run: echo "Building using docker"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running test cases
        run: echo "Testing the app"
  deploy:
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:
      - name: Deploy the app
        run: echo "Deploying the app"
    
